include:
  - package:deminearchiver_lints/analysis_options_flutter.yaml
  - package:deminearchiver_lints/app/loose.yaml

# TODO: remove after migrating away from the dynamic type.
analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
