targets:
  $default:
    builders:
      flutter_gen_runner:
        options:
          output: lib/assets/
          line_length: 80

          parse_metadata: true

          images:
            parse_animation: true

          fonts:
              outputs:
                package_parameter_enabled: false

          assets:
            outputs:
              package_parameter_enabled: false
              directory_path_enabled: true

          integrations:
            image: true
            flutter_svg: true
            lottie: false
            rive: false
      drift_dev:
        options:
          databases:
            materium: lib/database/database.dart
          schema_dir: drift_schemas/
      slang_build_runner:
        options:
          base_locale: en
          fallback_strategy: base_locale_empty_string

          input_directory: assets/i18n
          input_file_pattern: .json
          output_directory: lib/i18n

          flat_map: false

          imports:
            - package:materium/flutter.dart
          contexts: {}

          obfuscation:
            enabled: false

          format:
            enabled: true
            width: 80
