name: materium
description: Get Android app updates straight from the source.
version: 1.4.0+2332
homepage: https://github.com/deminearchiver/materium
repository: https://github.com/deminearchiver/materium
issue_tracker: https://github.com/deminearchiver/materium/issues
publish_to: none

workspace: []

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Git dependencies
  layout:
    git:
      url: https://github.com/deminearchiver/dart-flutter-packages.git
      ref: 7cd8db64c18455837a8d9aee34c4c7004067e6c0
      path: packages/layout
  material:
    git:
      url: https://github.com/deminearchiver/dart-flutter-packages.git
      ref: 7cd8db64c18455837a8d9aee34c4c7004067e6c0
      path: packages/material
  android_package_installer: # TODO: See if PR will be accepted (dev may not be active), else remove this comment
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: c9e144fae63231b5d1d7b88af779c314afcb6e83
  android_package_manager: # TODO: Make PR and switch to upstream
    git:
      url: https://github.com/ImranR98/android_package_manager
      ref: 18231a8a2343747440b0bfe90f7d56ef7f586099
  shared_storage: # TODO: Is this maintained?
    git:
      url: https://github.com/AlexBacich/shared-storage
      ref: 012e22791138958e089f6c1a8d6c4c6943a9f253
  shizuku_apk_installer:
    git:
      url: https://github.com/re7gog/shizuku_apk_installer
      ref: 3ef7f8fbf904848d144304556b0f80c91fee82a5

  # Hosted dependencies
  meta: ^1.18.2
  path_provider: ^2.1.5
  flutter_fgbg: ^0.8.0
  flutter_local_notifications: ^21.0.0
  provider: ^6.1.5+1
  http: ^1.6.0
  webview_flutter: ^4.13.1
  html: ^0.15.6
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  file_picker: ^11.0.2
  share_plus: ^12.0.2
  sqflite: ^2.4.2
  easy_localization: ^3.0.8
  android_intent_plus: ^6.0.0
  flutter_archive: ^6.0.4
  hsluv: ^1.1.3
  connectivity_plus: ^7.1.1
  crypto: ^3.0.7
  bcrypt: ^1.2.0
  app_links: ^7.0.0
  background_fetch: ^1.5.1
  flex_color_picker: ^3.8.0
  markdown: ^7.3.1
  flutter_typeahead: ^6.0.0
  battery_plus: ^7.0.0
  flutter_charset_detector: ^5.0.0
  flutter_foreground_task: ^9.2.2
  flutter_markdown_plus: ^1.0.7
  skeletonizer: ^2.1.3
  super_keyboard: ^0.4.0
  super_editor: ^0.3.0-dev.51
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  flutter_svg: ^2.2.4
  vector_graphics: ^1.1.21
  collection: ^1.19.1
  syntax_highlight: ^0.5.0
  drift: ^2.32.1
  drift_flutter: ^0.3.0
  drift_sqflite: ^2.0.1
  talker_flutter: ^5.1.16
  device_info_ffi: ^1.1.1
  dynamic_color_ffi: ^1.1.2
  screen_corners_ffi: ^1.1.1
  slang: ^4.14.0
  slang_flutter: ^4.14.0
  pub_semver: ^2.2.0
  motor: ^1.1.0

dev_dependencies:
  # Hosted dependencies
  deminearchiver_lints: ^2.1.2
  build_runner: ^2.13.1
  json_serializable: ^6.13.1
  freezed: ^3.2.5
  flutter_gen_runner: ^5.13.0+1
  drift_dev: ^2.32.1
  slang_build_runner: ^4.14.0
  fastforge: ^0.6.6

dependency_overrides:
  # Hosted dependencies
  archive: ^4.0.7 # fastforge uses outdated version
  device_info_plus: ^12.3.0 # Needed for unknown reasons
  material_color_utilities: ^0.13.0 # Flutter pinned dependency
  meta: ^1.18.0 # Always use latest version
  uuid: ^4.5.2 # fastforge uses outdated version
  super_editor: 0.3.0-dev.50
  super_keyboard: ^0.3.1

flutter:
  uses-material-design: true
  generate: false
  assets:
    # Certificates
    - assets/ca/

    # Graphics
    - assets/graphics/

    # App icons
    - assets/ic_launcher/

    # Translation files for easy_localization
    - assets/translations/

    # Open Font Licenses
    - assets/fonts/firacode/OFL.txt
    - assets/fonts/googlesans/OFL.txt
    - assets/fonts/googlesanscode/OFL.txt
    - assets/fonts/googlesansflex/OFL.txt
    - assets/fonts/robotoflex/OFL.txt
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/firacode/FiraCode-VariableFont_wght.ttf
          style: normal
    - family: Google Sans
      fonts:
        - asset: assets/fonts/googlesans/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
          style: normal
        - asset: assets/fonts/googlesans/GoogleSans-Italic-VariableFont_GRAD,opsz,wght.ttf
          style: italic
    - family: Google Sans Code
      fonts:
        - asset: assets/fonts/googlesanscode/GoogleSansCode-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/googlesanscode/GoogleSansCode-Italic-VariableFont_wght.ttf
          style: italic
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/googlesansflex/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
    - family: Monaspace Argon
      fonts:
        - asset: assets/fonts/monaspace/MonaspaceArgon-VariableFont.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/robotoflex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
