// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `dev.deminearchiver.screen_corners_ffi.ScreenCorners$Companion`
class ScreenCorners$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ScreenCorners$Companion> $type;

  @jni$_.internal
  ScreenCorners$Companion.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenCorners$Companion?> nullableType =
      $ScreenCorners$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenCorners$Companion> type =
      $ScreenCorners$Companion$Type$();
  static final _id_fromActivity = _class.instanceMethodId(
    r'fromActivity',
    r'(Landroid/app/Activity;)Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;',
  );

  static final _fromActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun fromActivity(activity: android.app.Activity): dev.deminearchiver.screen_corners_ffi.ScreenCorners`
  /// The returned object must be released after use, by calling the [release] method.
  ScreenCorners fromActivity(jni$_.JObject activity) {
    final _$activity = activity.reference;
    return _fromActivity(
      reference.pointer,
      _id_fromActivity as jni$_.JMethodIDPtr,
      _$activity.pointer,
    ).object<ScreenCorners>(const $ScreenCorners$Type$());
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners$Companion(jni$_.JObject? defaultConstructorMarker) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return ScreenCorners$Companion.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }
}

final class $ScreenCorners$Companion$NullableType$
    extends jni$_.JType<ScreenCorners$Companion?> {
  @jni$_.internal
  const $ScreenCorners$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion;';

  @jni$_.internal
  @core$_.override
  ScreenCorners$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : ScreenCorners$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ScreenCorners$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ScreenCorners$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ScreenCorners$Companion$NullableType$) &&
        other is $ScreenCorners$Companion$NullableType$;
  }
}

final class $ScreenCorners$Companion$Type$
    extends jni$_.JType<ScreenCorners$Companion> {
  @jni$_.internal
  const $ScreenCorners$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion;';

  @jni$_.internal
  @core$_.override
  ScreenCorners$Companion fromReference(jni$_.JReference reference) =>
      ScreenCorners$Companion.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ScreenCorners$Companion?> get nullableType =>
      const $ScreenCorners$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ScreenCorners$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ScreenCorners$Companion$Type$) &&
        other is $ScreenCorners$Companion$Type$;
  }
}

/// from: `dev.deminearchiver.screen_corners_ffi.ScreenCorners`
class ScreenCorners extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ScreenCorners> $type;

  @jni$_.internal
  ScreenCorners.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/deminearchiver/screen_corners_ffi/ScreenCorners',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenCorners?> nullableType =
      $ScreenCorners$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenCorners> type = $ScreenCorners$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners$Companion;',
  );

  /// from: `static public final dev.deminearchiver.screen_corners_ffi.ScreenCorners$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static ScreenCorners$Companion get Companion =>
      _id_Companion.get(_class, const $ScreenCorners$Companion$Type$());

  static final _id_new$ = _class.constructorId(
    r'(Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(java.lang.Double double, java.lang.Double double1, java.lang.Double double2, java.lang.Double double3)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
    jni$_.JDouble? double2,
    jni$_.JDouble? double3,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    final _$double2 = double2?.reference ?? jni$_.jNullReference;
    final _$double3 = double3?.reference ?? jni$_.jNullReference;
    return ScreenCorners.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$double.pointer,
        _$double1.pointer,
        _$double2.pointer,
        _$double3.pointer,
      ).reference,
    );
  }

  static final _id_new$1 = _class.constructorId(
    r'(Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;ILkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `synthetic public void <init>(java.lang.Double double, java.lang.Double double1, java.lang.Double double2, java.lang.Double double3, int i, kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners.new$1(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
    jni$_.JDouble? double2,
    jni$_.JDouble? double3,
    int i,
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    final _$double2 = double2?.reference ?? jni$_.jNullReference;
    final _$double3 = double3?.reference ?? jni$_.jNullReference;
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return ScreenCorners.fromReference(
      _new$1(
        _class.reference.pointer,
        _id_new$1 as jni$_.JMethodIDPtr,
        _$double.pointer,
        _$double1.pointer,
        _$double2.pointer,
        _$double3.pointer,
        i,
        _$defaultConstructorMarker.pointer,
      ).reference,
    );
  }

  static final _id_getTopLeft = _class.instanceMethodId(
    r'getTopLeft',
    r'()Ljava/lang/Double;',
  );

  static final _getTopLeft =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getTopLeft()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? getTopLeft() {
    return _getTopLeft(
      reference.pointer,
      _id_getTopLeft as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_getTopRight = _class.instanceMethodId(
    r'getTopRight',
    r'()Ljava/lang/Double;',
  );

  static final _getTopRight =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getTopRight()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? getTopRight() {
    return _getTopRight(
      reference.pointer,
      _id_getTopRight as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_getBottomLeft = _class.instanceMethodId(
    r'getBottomLeft',
    r'()Ljava/lang/Double;',
  );

  static final _getBottomLeft =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getBottomLeft()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? getBottomLeft() {
    return _getBottomLeft(
      reference.pointer,
      _id_getBottomLeft as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_getBottomRight = _class.instanceMethodId(
    r'getBottomRight',
    r'()Ljava/lang/Double;',
  );

  static final _getBottomRight =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getBottomRight()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? getBottomRight() {
    return _getBottomRight(
      reference.pointer,
      _id_getBottomRight as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_component1 = _class.instanceMethodId(
    r'component1',
    r'()Ljava/lang/Double;',
  );

  static final _component1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component1(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component1() {
    return _component1(
      reference.pointer,
      _id_component1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_component2 = _class.instanceMethodId(
    r'component2',
    r'()Ljava/lang/Double;',
  );

  static final _component2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component2(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component2() {
    return _component2(
      reference.pointer,
      _id_component2 as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_component3 = _class.instanceMethodId(
    r'component3',
    r'()Ljava/lang/Double;',
  );

  static final _component3 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component3(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component3() {
    return _component3(
      reference.pointer,
      _id_component3 as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_component4 = _class.instanceMethodId(
    r'component4',
    r'()Ljava/lang/Double;',
  );

  static final _component4 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public operator fun component4(): kotlin.Double?`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? component4() {
    return _component4(
      reference.pointer,
      _id_component4 as jni$_.JMethodIDPtr,
    ).object<jni$_.JDouble?>(const jni$_.$JDouble$NullableType$());
  }

  static final _id_copy = _class.instanceMethodId(
    r'copy',
    r'(Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;Ljava/lang/Double;)Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;',
  );

  static final _copy =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Pointer<jni$_.Void>,
                  )
                >,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun copy(topLeft: kotlin.Double?, topRight: kotlin.Double?, bottomLeft: kotlin.Double?, bottomRight: kotlin.Double?): dev.deminearchiver.screen_corners_ffi.ScreenCorners`
  /// The returned object must be released after use, by calling the [release] method.
  ScreenCorners copy(
    jni$_.JDouble? double,
    jni$_.JDouble? double1,
    jni$_.JDouble? double2,
    jni$_.JDouble? double3,
  ) {
    final _$double = double?.reference ?? jni$_.jNullReference;
    final _$double1 = double1?.reference ?? jni$_.jNullReference;
    final _$double2 = double2?.reference ?? jni$_.jNullReference;
    final _$double3 = double3?.reference ?? jni$_.jNullReference;
    return _copy(
      reference.pointer,
      _id_copy as jni$_.JMethodIDPtr,
      _$double.pointer,
      _$double1.pointer,
      _$double2.pointer,
      _$double3.pointer,
    ).object<ScreenCorners>(const $ScreenCorners$Type$());
  }

  static final _id_toString$1 = _class.instanceMethodId(
    r'toString',
    r'()Ljava/lang/String;',
  );

  static final _toString$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun toString(): kotlin.String`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JString toString$1() {
    return _toString$1(
      reference.pointer,
      _id_toString$1 as jni$_.JMethodIDPtr,
    ).object<jni$_.JString>(const jni$_.$JString$Type$());
  }

  static final _id_hashCode$1 = _class.instanceMethodId(r'hashCode', r'()I');

  static final _hashCode$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun hashCode(): kotlin.Int`
  int hashCode$1() {
    return _hashCode$1(
      reference.pointer,
      _id_hashCode$1 as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_equals = _class.instanceMethodId(
    r'equals',
    r'(Ljava/lang/Object;)Z',
  );

  static final _equals =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallBooleanMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public operator fun equals(other: kotlin.Any?): kotlin.Boolean`
  bool equals(jni$_.JObject? object) {
    final _$object = object?.reference ?? jni$_.jNullReference;
    return _equals(
      reference.pointer,
      _id_equals as jni$_.JMethodIDPtr,
      _$object.pointer,
    ).boolean;
  }

  static final _id_new$2 = _class.constructorId(r'()V');

  static final _new$2 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenCorners.new$2() {
    return ScreenCorners.fromReference(
      _new$2(
        _class.reference.pointer,
        _id_new$2 as jni$_.JMethodIDPtr,
      ).reference,
    );
  }

  static final _id_fromActivity = _class.staticMethodId(
    r'fromActivity',
    r'(Landroid/app/Activity;)Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;',
  );

  static final _fromActivity =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallStaticObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `static public final dev.deminearchiver.screen_corners_ffi.ScreenCorners fromActivity(android.app.Activity activity)`
  /// The returned object must be released after use, by calling the [release] method.
  static ScreenCorners fromActivity(jni$_.JObject activity) {
    final _$activity = activity.reference;
    return _fromActivity(
      _class.reference.pointer,
      _id_fromActivity as jni$_.JMethodIDPtr,
      _$activity.pointer,
    ).object<ScreenCorners>(const $ScreenCorners$Type$());
  }
}

final class $ScreenCorners$NullableType$ extends jni$_.JType<ScreenCorners?> {
  @jni$_.internal
  const $ScreenCorners$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;';

  @jni$_.internal
  @core$_.override
  ScreenCorners? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : ScreenCorners.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ScreenCorners?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ScreenCorners$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ScreenCorners$NullableType$) &&
        other is $ScreenCorners$NullableType$;
  }
}

final class $ScreenCorners$Type$ extends jni$_.JType<ScreenCorners> {
  @jni$_.internal
  const $ScreenCorners$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/deminearchiver/screen_corners_ffi/ScreenCorners;';

  @jni$_.internal
  @core$_.override
  ScreenCorners fromReference(jni$_.JReference reference) =>
      ScreenCorners.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ScreenCorners?> get nullableType =>
      const $ScreenCorners$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ScreenCorners$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ScreenCorners$Type$) &&
        other is $ScreenCorners$Type$;
  }
}
