package dev.deminearchiver.dynamic_color_ffi

import android.content.Context
import androidx.annotation.Keep

@Keep
class DynamicColorScheme(
  val primaryPaletteKeyColor: Int? = null,
  val secondaryPaletteKeyColor: Int? = null,
  val tertiaryPaletteKeyColor: Int? = null,
  val neutralPaletteKeyColor: Int? = null,
  val neutralVariantPaletteKeyColor: Int? = null,
  val errorPaletteKeyColor: Int? = null,
  val background: Int? = null,
  val onBackground: Int? = null,
  val surface: Int? = null,
  val surfaceDim: Int? = null,
  val surfaceBright: Int? = null,
  val surfaceContainerLowest: Int? = null,
  val surfaceContainerLow: Int? = null,
  val surfaceContainer: Int? = null,
  val surfaceContainerHigh: Int? = null,
  val surfaceContainerHighest: Int? = null,
  val onSurface: Int? = null,
  val surfaceVariant: Int? = null,
  val onSurfaceVariant: Int? = null,
  val outline: Int? = null,
  val outlineVariant: Int? = null,
  val inverseSurface: Int? = null,
  val inverseOnSurface: Int? = null,
  val shadow: Int? = null,
  val scrim: Int? = null,
  val surfaceTint: Int? = null,
  val primary: Int? = null,
  val primaryDim: Int? = null,
  val onPrimary: Int? = null,
  val primaryContainer: Int? = null,
  val onPrimaryContainer: Int? = null,
  val primaryFixed: Int? = null,
  val primaryFixedDim: Int? = null,
  val onPrimaryFixed: Int? = null,
  val onPrimaryFixedVariant: Int? = null,
  val inversePrimary: Int? = null,
  val secondary: Int? = null,
  val secondaryDim: Int? = null,
  val onSecondary: Int? = null,
  val secondaryContainer: Int? = null,
  val onSecondaryContainer: Int? = null,
  val secondaryFixed: Int? = null,
  val secondaryFixedDim: Int? = null,
  val onSecondaryFixed: Int? = null,
  val onSecondaryFixedVariant: Int? = null,
  val tertiary: Int? = null,
  val tertiaryDim: Int? = null,
  val onTertiary: Int? = null,
  val tertiaryContainer: Int? = null,
  val onTertiaryContainer: Int? = null,
  val tertiaryFixed: Int? = null,
  val tertiaryFixedDim: Int? = null,
  val onTertiaryFixed: Int? = null,
  val onTertiaryFixedVariant: Int? = null,
  val error: Int? = null,
  val errorDim: Int? = null,
  val onError: Int? = null,
  val errorContainer: Int? = null,
  val onErrorContainer: Int? = null,
)
