name: Build and publish nightly release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

concurrency:
  group: nightly
  cancel-in-progress: true

jobs:
  nightly:
    name: Build and publish nightly release
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Get Pub dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Build release APKs
        run: flutter build apk --release --split-per-abi

      # - name: Delete previous nightly version
      #   uses: ClementTsang/delete-tag-and-release@v0.4.0
      #   with:
      #     tag_name: "nightly"
      #     delete_release: true

      - name: Create nightly release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly
          name: nightly
          draft: false
          prerelease: true
          make_latest: false
          files: |
            build/app/outputs/flutter-apk/*.apk
            build/app/outputs/flutter-apk/*.apk.sha1
